version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tmdb_movie_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: movie_database
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d movie_database"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - movie_network_dev

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tmdb_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tmdb.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - movie_network_dev

  movie-collector:
    build: .
    container_name: tmdb_collector_dev
    restart: "no"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_BASE_URL=${TMDB_BASE_URL}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=movie_database
      - DB_USER=movie_user
      - DB_PASSWORD=movie_password
      - BATCH_SIZE=${BATCH_SIZE}
      - MAX_PAGES=${MAX_PAGES}
      - LANGUAGE=${LANGUAGE}
      - REGION=${REGION}
      - COLLECT_MOVIES=${COLLECT_MOVIES}
      - COLLECT_GENRES=${COLLECT_GENRES}
      - COLLECT_CREDITS=${COLLECT_CREDITS}
      - COLLECT_KEYWORDS=${COLLECT_KEYWORDS}
      - COLLECT_REVIEWS=${COLLECT_REVIEWS}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FILE=logs/movie_collector.log
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./.env:/app/.env:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - movie_network_dev
    command: ["python", "src/main.py", "--init-db", "--popular", "--max-pages", "5"]

volumes:
  postgres_data_dev:
    driver: local
  pgadmin_data_dev:
    driver: local

networks:
  movie_network_dev:
    driver: bridge
