version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tmdb_movie_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: movie_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d movie_database"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - movie_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tmdb_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - movie_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  movie_network:
    driver: bridge
